Repository Codess-Cafe/Codess-Website, pull requests merged in 2023-10, with the labels that each got.

#35 Updated index.html (Numbers Speak Louder section) Issue #26
  index.html
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#8 Update 'Apply' Section for Formatting and Terminology
  index.html
Labels: hacktoberfest, ready to merge

#16 update social links that appear on the left side of index.html
  index.html
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#17 Remove cards update footer
  index.html
  linkedin.html
  medium.html
  mentors.html
  twitter.html
  youtube.html
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#19 Issue #5 resolved (Space b/w section header & testimonal cards is added)
  style.css
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#30 added CONTRIBUTING.md file and edited README.md file
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#40 Closes #33
  style.css
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#41 Added hover effect on cards of "What our students say" section
  style.css
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#43 Fixed the alignment issue (Issue#10)
  style.css
Labels: hacktoberfest, changes requested

#34 Added animation in texts
  app.js
  index.html
  style.css
Labels: hacktoberfest, changes requested

#52 Fix: Changed the Twitter logo
  index.html
  linkedin.html
  medium.html
  mentors.html
  style.css
  twitter.html
  youtube.html
Labels: hacktoberfest, ready to merge

#36 issue #4 Revise Team Member Information
  images/mentor/39.jpeg
  images/mentor/39.jpg
  images/mentor/45.jpg
  index.html
Labels: hacktoberfest, changes requested

#53 Fixed: mentorship matters heading
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#62 Added animation-on-scroll to the Mentorship Matters Section[Issue#61]
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#57 Feat/faq expandable
  app.js
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#70 Added counterup in Numbers Speak Louder Section[Issue#64]
  app.js
  index.html
Labels: hacktoberfest, hacktoberfest accepted

#84 Enhanced FAQ section
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#81 Added hover effect to navbar links
  style.css
Labels: hacktoberfest, hacktoberfest accepted, ready to merge

#76 Issue No. Codess-Cafe#59 Fixed
  style.css
Labels: hacktoberfest, changes requested

#78 Enhanced the Alignment of Chapter Cards #12
  index.html
  style.css
Labels: hacktoberfest, changes requested

#92 smooth transition of social icons(fixed#86)
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#87 Responsive, for Meet The Team Section
  style.css
Labels: hacktoberfest

#75 About Us CTA added
  custom.css
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest accepted

#101 Added hover effect to the program offerings
  style.css
Labels: question, hacktoberfest

#96 Adding Hover to socail media link
  style.css
Labels: hacktoberfest, changes requested
